# Generated by Django 5.2.6 on 2025-09-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('area_sqm', models.FloatField()),
                ('deed_picture', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NUL', 'NULL'), ('CHK', 'CHECK'), ('FAL', 'FAIL'), ('PAS', 'PASS'), ('BUY', 'BUY')], default='NUL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('main_contact', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CondoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condo.condo')),
            ],
        ),
        migrations.AddField(
            model_name='condo',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condo.province'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='condo.role')),
            ],
        ),
        migrations.CreateModel(
            name='CondoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condo.condo')),
                ('author', models.ManyToManyField(to='condo.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CondoListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condo.condo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condo.user')),
            ],
        ),
    ]
